# Text classification using GaussianNB, Random Forest, and Roberta

Text Classification: In this project the author implemented different machine learning models for text classsification on the *IMDB Dataset of 50K Movie Reviews*. The dataset is available on kaggle. First of all implemented the text  pre-processing including (missing values, duplicates, tags removal, lower case etc). Then GaussianNB, random forest and roberta with number of differnet techniques to increase the accuracy.

Applied transformer model but as we all know that transformer models requires huge memory, even though I reduced the dataset furthermore, but still I was unable to fully executes the model. 


In [2]:
# importing required libraries
import numpy as np
import pandas as pd

In [3]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
data_frame = pd.read_csv('/content/drive/MyDrive/IMDB Dataset.csv')

In [ ]:
data_frame = pd.read_csv('C:/Users/Toma Shah/Downloads/txt classification/IMDB Dataset.csv')

In [5]:
#due to memory issues instead of using whole data, I have used limited dataset
# data_frame = data_frame.iloc[:15000]
data_frame = data_frame.iloc[:10000]

In [ ]:
data_frame.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
data_frame['review'][10]

'Phil the Alien is one of those quirky films where the humour is based around the oddness of everything rather than actual punchlines.<br /><br />At first it was very odd and pretty funny but as the movie progressed I didn\'t find the jokes or oddness funny anymore.<br /><br />Its a low budget film (thats never a problem in itself), there were some pretty interesting characters, but eventually I just lost interest.<br /><br />I imagine this film would appeal to a stoner who is currently partaking.<br /><br />For something similar but better try "Brother from another planet"'

In [5]:
data_frame['sentiment'].value_counts() #checking the balance of data

negative    7609
positive    7391
Name: sentiment, dtype: int64

In [6]:
data_frame.isnull().sum() #checking null values

review       0
sentiment    0
dtype: int64

In [7]:
data_frame.duplicated().sum() # checking duplicate values

39

In [6]:
data_frame = data_frame.drop_duplicates(inplace=False) # dropping the duplicate values


In [9]:
data_frame.duplicated().sum()

0

Basic Preprocessing includes removing tags, coverting whole data into lower case and removing stopwords.

In [7]:
# removing tags function
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [8]:
data_frame['review'] = data_frame['review'].apply(remove_tags)

In [ ]:
data_frame

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
14995  Bobcat Goldthwait should be commended for atte...  negative
14996  And it's not because since her days on "Claris...  positive
14997  A traveling couple (Horton and Hamilton)stumbl...  negative
14998  This film is deeply disappointing. Not only th...  negative
14999  The revelation here is Lana Turner's dancing a...  positive

[14961 rows x 2 columns]

In [9]:
# coverting whole data to lower case
data_frame['review'] = data_frame['review'].apply(lambda x:x.lower())

In [13]:
# Download the stopwords resource
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [10]:
from nltk.corpus import stopwords

In [11]:
sw_list = stopwords.words('english')

data_frame['review'] = data_frame['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [ ]:
data_frame

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production. filming technique...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
14995  bobcat goldthwait commended attempting somethi...  negative
14996  since days "clarissa explains all" i've bit cr...  positive
14997  traveling couple (horton hamilton)stumble onto...  negative
14998  film deeply disappointing. wenders displays li...  negative
14999  revelation lana turner's dancing ability. thou...  positive

[14961 rows x 2 columns]

In [12]:
X = data_frame.iloc[:,0:1]
y = data_frame['sentiment']

In [ ]:
X.shape

(14961, 1)

In [ ]:
X

review
0      one reviewers mentioned watching 1 oz episode ...
1      wonderful little production. filming technique...
2      thought wonderful way spend time hot summer we...
3      basically there's family little boy (jake) thi...
4      petter mattei's "love time money" visually stu...
...                                                  ...
14995  bobcat goldthwait commended attempting somethi...
14996  since days "clarissa explains all" i've bit cr...
14997  traveling couple (horton hamilton)stumble onto...
14998  film deeply disappointing. wenders displays li...
14999  revelation lana turner's dancing ability. thou...

[14961 rows x 1 columns]

In [ ]:
y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
14995    negative
14996    positive
14997    negative
14998    negative
14999    positive
Name: sentiment, Length: 14961, dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [18]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1) # splitting data for model

In [ ]:
X_train.shape

(11968, 1)

In [ ]:
# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [ ]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [ ]:
X_train_bow.shape

(11968, 57303)

In [ ]:
from sklearn.naive_bayes import GaussianNB

# applying GaussiianNB

gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6625459405278984

Accuracy of GassianNB is too low, but as I have stated earlier that I didnot use the whole dataset

In [ ]:
confusion_matrix(y_test,y_pred)

array([[1144,  359],
       [ 651,  839]], dtype=int64)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier() # defning instance of random forest

In [ ]:
rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8456398262612763

Random forest accuracy is increased as compared to gaussianNB, If we applied RF using the whole dataset its accuracy will still be better than GassuianNB.

CountVectorizer is a class from scikit-learn that converts a collection of text documents to a matrix of token counts. It counts the occurrences of each word (token) in the document.

max_features=3000 is an optional parameter that limits the number of features (unique words) to the top 3000 most frequent words. This is done to reduce the dimensionality of the feature space.

In [ ]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [ ]:
rf = RandomForestClassifier()

In [ ]:
rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8419645840294019

ngram_range=(1, 2): This parameter specifies that you want to consider both unigrams (individual words) and bigrams (two consecutive words) when creating the token counts. For example, if you have the sentence "I love natural language processing," the n-grams would include "I," "love," "natural," "language," "processing," "I love," "love natural," "natural language," and so on.

max_features=5000: This parameter limits the number of features (unique n-grams) to the top 5000 most frequent ones. This helps control the dimensionality of the feature space.

In [ ]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [ ]:
rf = RandomForestClassifier()

In [ ]:
rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8416304710992315

## Using TfIdf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [ ]:
rf = RandomForestClassifier()

In [ ]:
rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8506515202138323

## Using word2vec

In [ ]:
import gensim

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
story = []
for doc in data_frame['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [ ]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [ ]:
model.build_vocab(story)

In [ ]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(8861242, 9333340)

In [ ]:
len(model.wv.index_to_key)

38121

In [ ]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [ ]:
document_vector(data_frame['review'].values[0])

array([-0.1062387 ,  0.57879865, -0.09218969,  0.14872472,  0.07653671,
       -0.36878502,  0.21240993,  0.57078224, -0.4596878 , -0.08611797,
       -0.13649575, -0.42002127,  0.14361812,  0.43518403,  0.0962563 ,
       -0.20527296,  0.19676772, -0.43193722, -0.13806553, -0.63291574,
        0.16427596,  0.11688622,  0.01411404, -0.10233656, -0.29268107,
       -0.23124242, -0.08162528, -0.09489606, -0.24155933,  0.07943141,
        0.40588522, -0.05339793, -0.11622055, -0.18573867, -0.31042463,
        0.4238689 , -0.05564627, -0.5161315 , -0.13030896, -0.7088889 ,
       -0.00226183, -0.08960303, -0.02157499, -0.15973948,  0.3398637 ,
       -0.05734019, -0.25960734, -0.23065479,  0.1594725 ,  0.21978083,
        0.08158969, -0.3287221 , -0.20053041, -0.14732364, -0.25804818,
        0.417201  ,  0.32288316, -0.04442431, -0.26429772,  0.07237586,
       -0.16668832,  0.06561849, -0.21513058,  0.17991115, -0.27956894,
        0.1917376 ,  0.11000454,  0.180633  , -0.2990877 ,  0.38

In [ ]:
from tqdm import tqdm

In [ ]:
X = []
for doc in tqdm(data_frame['review'].values):
    X.append(document_vector(doc))

100%|████████████████████████████████████████████████████████████████████████████| 14961/14961 [21:58<00:00, 11.34it/s]


In [ ]:
X = np.array(X)

In [ ]:
X[0]

array([-0.1062387 ,  0.57879865, -0.09218969,  0.14872472,  0.07653671,
       -0.36878502,  0.21240993,  0.57078224, -0.4596878 , -0.08611797,
       -0.13649575, -0.42002127,  0.14361812,  0.43518403,  0.0962563 ,
       -0.20527296,  0.19676772, -0.43193722, -0.13806553, -0.63291574,
        0.16427596,  0.11688622,  0.01411404, -0.10233656, -0.29268107,
       -0.23124242, -0.08162528, -0.09489606, -0.24155933,  0.07943141,
        0.40588522, -0.05339793, -0.11622055, -0.18573867, -0.31042463,
        0.4238689 , -0.05564627, -0.5161315 , -0.13030896, -0.7088889 ,
       -0.00226183, -0.08960303, -0.02157499, -0.15973948,  0.3398637 ,
       -0.05734019, -0.25960734, -0.23065479,  0.1594725 ,  0.21978083,
        0.08158969, -0.3287221 , -0.20053041, -0.14732364, -0.25804818,
        0.417201  ,  0.32288316, -0.04442431, -0.26429772,  0.07237586,
       -0.16668832,  0.06561849, -0.21513058,  0.17991115, -0.27956894,
        0.1917376 ,  0.11000454,  0.180633  , -0.2990877 ,  0.38

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(data_frame['sentiment'])

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
rf = RandomForestClassifier()

In [ ]:
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7888406281323087

# Applying Transformer model RoBERTa

In [19]:
!pip install torch
!pip install transformers
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 20.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 36.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 51.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 47.2 MB/s eta 0:00:00


In [13]:
from sklearn.model_selection import train_test_split
from transformers import RobertaTokenizer, RobertaForSequenceClassification, AdamW
import torch

In [14]:
# Split the dataset into training and testing sets
train_texts, test_texts, train_labels, test_labels = train_test_split(data_frame['review'], data_frame['sentiment'], test_size=0.2, random_state=42)


In [15]:
# Convert labels to numerical format (assuming binary classification)
label_mapping = {'positive': 1, 'negative': 0}
train_labels = train_labels.map(label_mapping)
test_labels = test_labels.map(label_mapping)

In [16]:
# Print some information about the labels
print("Train Labels Info:")
print(train_labels.value_counts())

Train Labels Info:
1    4011
0    3975
Name: sentiment, dtype: int64


In [17]:
# Load RoBERTa tokenizer
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

In [18]:
# Tokenize input texts
train_encodings = tokenizer(train_texts.tolist(), truncation=True, padding=True, max_length=512, return_tensors='pt')
test_encodings = tokenizer(test_texts.tolist(), truncation=True, padding=True, max_length=512, return_tensors='pt')

In [19]:
# Create PyTorch tensors for labels
train_labels = torch.tensor(train_labels.tolist())
test_labels = torch.tensor(test_labels.tolist())

In [20]:
model = RobertaForSequenceClassification.from_pretrained('roberta-base', num_labels=2)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.out_proj.bias', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
optimizer = AdamW(model.parameters(), lr=5e-5)

# Train the model
for epoch in range(3):  # Adjust the number of epochs as needed
    outputs = model(**train_encodings, labels=train_labels)
    loss = outputs.loss
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
with torch.no_grad():
    outputs = model(**test_encodings, labels=test_labels)
    predictions = torch.argmax(outputs.logits, dim=1)